import { test } from 'node:test';
import assert from 'node:assert/strict';
import { existsSync } from 'node:fs';
import { mkdir, mkdtemp, readdir, readFile, rm, symlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join, relative } from 'node:path';
import { planInstall } from '../src/harnesses.js';
import { applyPlan } from '../src/install.js';
import { findBot, findInstalled, removeBot } from '../src/remove.js';
import { studyBuddy } from './helpers.js';

const tempHome = () => mkdtemp(join(tmpdir(), 'grokport-remove-'));
const STUDY_BUDDY_URL = 'https://x.ai/bot/AbCdEfGhIjKlMnOpQrStU';
const OTHER_URL = 'https://x.ai/bot/ZZZZZZZZZZZZZZZZZZZZZ';
/** A different bot that happens to have the same name. */
const anotherStudyBuddy = () => ({ ...studyBuddy(), id: 'ZZZZZZZZZZZZZZZZZZZZZ', url: OTHER_URL });
const nightOwl = () => ({
  ...studyBuddy(),
  id: 'NNNNNNNNNNNNNNNNNNNNN',
  url: 'https://x.ai/bot/NNNNNNNNNNNNNNNNNNNNN',
  name: 'Night Owl',
  slug: 'night-owl',
});

/** Installs a bot the way `npx grokport <link> --to <agents> -y` does. */
async function install(home, agents, bot = studyBuddy()) {
  const results = await applyPlan(planInstall(bot, agents, { home, cwd: home }));
  assert.ok(
    results.every((result) => result.ok),
    'installed',
  );
}

/** Every file under `dir`, sorted, with forward slashes. */
async function filesIn(dir) {
  const entries = await readdir(dir, { recursive: true, withFileTypes: true });
  return entries
    .filter((entry) => entry.isFile())
    .map((entry) => relative(dir, join(entry.parentPath, entry.name)).replaceAll('\\', '/'))
    .sort();
}

test('finds a bot in every place install can put it', async () => {
  const home = await tempHome();
  for (const agent of ['claude', 'codex', 'cursor', 'gemini', 'opencode', 'copilot', 'grok']) {
    await install(home, [agent]);
  }

  const bots = await findInstalled(home);

  assert.deepEqual(
    bots.map((bot) => [bot.name, bot.source]),
    [['Study Buddy', STUDY_BUDDY_URL]],
  );
  assert.deepEqual(
    bots[0].items.map((item) => item.path).sort(),
    [
      join(home, '.agents', 'skills', 'study-buddy'),
      join(home, '.claude', 'agents', 'study-buddy.md'),
      join(home, '.claude', 'skills', 'study-buddy'),
      join(home, '.config', 'opencode', 'agents', 'study-buddy.md'),
      join(home, '.config', 'opencode', 'skills', 'study-buddy'),
      join(home, '.copilot', 'skills', 'study-buddy'),
      join(home, '.cursor', 'skills', 'study-buddy'),
      join(home, '.gemini', 'skills', 'study-buddy'),
      join(home, '.grok', 'skills', 'study-buddy'),
    ].sort(),
  );
});

test("lists each bot once, and skips skills grokport didn't make", async () => {
  const home = await tempHome();
  await install(home, ['claude', 'codex']);
  await install(home, ['gemini'], nightOwl());
  const mySkill = join(home, '.claude', 'skills', 'my-skill', 'SKILL.md');
  await mkdir(dirname(mySkill), { recursive: true });
  await writeFile(mySkill, '---\nname: my-skill\n---\nMy own skill.\n');
  // A note with terminal control codes in its link was never written by grokport.
  const sneaky = join(home, '.claude', 'skills', 'sneaky', 'SKILL.md');
  await mkdir(dirname(sneaky), { recursive: true });
  await writeFile(
    sneaky,
    '# Sneaky\n\n<!-- generated by grokport from https://x.ai/bot/\x1b[2JAAAAAAAAAAAAAAAAAAAAA. Reinstalling replaces this file. -->\n',
  );
  // grokport names persona files after the bot, so a file with a name it could never write isn't its own.
  const persona = await readFile(join(home, '.claude', 'agents', 'study-buddy.md'), 'utf8');
  await writeFile(join(home, '.claude', 'agents', 'Study Buddy copy.md'), persona);

  const bots = await findInstalled(home);

  assert.deepEqual(
    bots.map((bot) => [bot.name, bot.source, bot.items.length]),
    [
      ['Night Owl', 'https://x.ai/bot/NNNNNNNNNNNNNNNNNNNNN', 1],
      ['Study Buddy', STUDY_BUDDY_URL, 3],
    ],
  );
});

test('finds the bot you mean by its name or its link', async () => {
  const home = await tempHome();
  const noLatinLetters = {
    ...studyBuddy(),
    id: 'KKKKKKKKKKKKKKKKKKKKK',
    url: 'https://x.ai/bot/KKKKKKKKKKKKKKKKKKKKK',
    name: '学习伙伴',
    slug: 'grok-bot',
  };
  await install(home, ['claude']);
  await install(home, ['claude'], nightOwl());
  await install(home, ['claude'], noLatinLetters);
  const bots = await findInstalled(home);

  for (const wanted of ['study-buddy', 'Study Buddy', '  STUDY BUDDY ', STUDY_BUDDY_URL, 'AbCdEfGhIjKlMnOpQrStU']) {
    assert.equal(findBot(bots, wanted).source, STUDY_BUDDY_URL, wanted);
  }
  assert.equal(findBot(bots, '学习伙伴').source, 'https://x.ai/bot/KKKKKKKKKKKKKKKKKKKKK');
  for (const wanted of ['study', 'Study Buddy 2', 'https://x.ai/bot/NIEguoGUjA648fUPle8F5']) {
    assert.throws(() => findBot(bots, wanted), { code: 'not-found' }, wanted);
  }
});

test('asks for the link when two different bots have the name you gave', async () => {
  const home = await tempHome();
  await install(home, ['claude']);
  await install(home, ['codex'], anotherStudyBuddy());
  const bots = await findInstalled(home);

  assert.throws(
    () => findBot(bots, 'study-buddy'),
    (error) =>
      error.code === 'ambiguous' && error.message.includes(STUDY_BUDDY_URL) && error.message.includes(OTHER_URL),
  );
  assert.equal(findBot(bots, OTHER_URL).source, OTHER_URL);
});

test('removes every file and folder it installed for the bot', async () => {
  const home = await tempHome();
  await install(home, ['claude', 'codex', 'opencode']);
  const [bot] = await findInstalled(home);

  const results = await removeBot(bot);

  assert.deepEqual(
    results.map((result) => [result.ok, result.kept]),
    [
      [true, false],
      [true, false],
      [true, false],
      [true, false],
    ],
  );
  for (const path of [
    join(home, '.claude', 'skills', 'study-buddy'),
    join(home, '.agents', 'skills', 'study-buddy'),
    join(home, '.claude', 'agents', 'study-buddy.md'),
    join(home, '.config', 'opencode', 'agents', 'study-buddy.md'),
  ]) {
    assert.equal(existsSync(path), false, path);
  }
  assert.ok(existsSync(join(home, '.claude', 'skills')), 'the skills folder itself stays');
});

test('removes playbook folders that an update left empty', async () => {
  const home = await tempHome();
  await install(home, ['claude']);
  await install(home, ['claude'], { ...studyBuddy(), skills: [], routines: [], starterSkill: undefined });
  const [bot] = await findInstalled(home);

  const results = await removeBot(bot);

  assert.deepEqual(
    results.map((result) => [result.ok, result.kept]),
    [
      [true, false],
      [true, false],
    ],
  );
  assert.equal(existsSync(join(home, '.claude', 'skills', 'study-buddy')), false);
});

test("still works when you already deleted some of the bot's files yourself", async () => {
  const home = await tempHome();
  await install(home, ['claude', 'codex']);
  await rm(join(home, '.claude', 'skills', 'study-buddy', 'skills', 'weekly-plan.md'));
  const [bot] = await findInstalled(home);
  await rm(join(home, '.agents', 'skills', 'study-buddy'), { recursive: true });
  await rm(join(home, '.claude', 'agents', 'study-buddy.md'));

  const results = await removeBot(bot);

  assert.deepEqual(
    results.map((result) => result.ok),
    [true, true, true],
  );
  assert.equal(existsSync(join(home, '.claude', 'skills', 'study-buddy')), false);
});

test('keeps files you added to the bot folder, and the folder that holds them', async () => {
  const home = await tempHome();
  await install(home, ['claude']);
  const folder = join(home, '.claude', 'skills', 'study-buddy');
  await writeFile(join(folder, 'my-notes.md'), 'notes\n');
  await writeFile(join(folder, 'skills', 'my-own-playbook.md'), 'mine\n');
  const [bot] = await findInstalled(home);

  const results = await removeBot(bot);

  assert.deepEqual(
    results.map((result) => [result.item.kind, result.ok, result.kept]),
    [
      ['bundle', true, true],
      ['file', true, false],
    ],
  );
  assert.deepEqual(await filesIn(folder), ['my-notes.md', 'skills/my-own-playbook.md']);
  assert.equal(existsSync(join(folder, 'routines')), false);
});

test('the bot can be added again after remove kept a folder for your files', async () => {
  const home = await tempHome();
  await install(home, ['claude']);
  const folder = join(home, '.claude', 'skills', 'study-buddy');
  await writeFile(join(folder, 'my-notes.md'), 'notes\n');
  await removeBot((await findInstalled(home))[0]);

  await install(home, ['claude']);

  assert.equal(await readFile(join(folder, 'my-notes.md'), 'utf8'), 'notes\n');
  assert.deepEqual(
    (await findInstalled(home)).map((bot) => bot.items.length),
    [2],
  );
});

test('keeps SKILL.md when a delete fails halfway, so remove can finish later', async () => {
  const home = await tempHome();
  await install(home, ['claude']);
  // A folder where a playbook file should be makes deleting that playbook fail.
  const playbook = join(home, '.claude', 'skills', 'study-buddy', 'skills', 'weekly-plan.md');
  await rm(playbook);
  await mkdir(playbook);
  await writeFile(join(playbook, 'inside.md'), 'inside\n');
  const [bot] = await findInstalled(home);

  const [skillFolder] = await removeBot(bot);

  assert.equal(skillFolder.ok, false);
  assert.deepEqual(
    (await findInstalled(home)).map((found) => found.source),
    [STUDY_BUDDY_URL],
  );
});

test("leaves alone skills it didn't make, even ones with the same name", async () => {
  const home = await tempHome();
  await install(home, ['claude']);
  await install(home, ['codex'], anotherStudyBuddy());
  const mySkill = join(home, '.cursor', 'skills', 'study-buddy', 'SKILL.md');
  await mkdir(dirname(mySkill), { recursive: true });
  await writeFile(mySkill, '---\nname: study-buddy\n---\nMy own skill.\n');

  await removeBot(findBot(await findInstalled(home), STUDY_BUDDY_URL));

  assert.equal(existsSync(join(home, '.claude', 'skills', 'study-buddy')), false);
  assert.equal(await readFile(mySkill, 'utf8'), '---\nname: study-buddy\n---\nMy own skill.\n');
  assert.deepEqual(
    (await findInstalled(home)).map((bot) => bot.source),
    [OTHER_URL],
  );
});

test("leaves alone a copy of the bot's folder saved under another name", async () => {
  const home = await tempHome();
  await install(home, ['claude']);
  const skill = await readFile(join(home, '.claude', 'skills', 'study-buddy', 'SKILL.md'), 'utf8');
  const copy = join(home, '.claude', 'skills', 'my-study-buddy', 'SKILL.md');
  await mkdir(dirname(copy), { recursive: true });
  await writeFile(copy, skill.replace('name: "study-buddy"', 'name: "my-study-buddy"'));
  const [bot] = await findInstalled(home);

  await removeBot(bot);

  assert.equal(await readFile(copy, 'utf8'), skill.replace('name: "study-buddy"', 'name: "my-study-buddy"'));
  assert.equal(existsSync(join(home, '.claude', 'skills', 'study-buddy')), false);
});

test('checks each file again right before deleting it', async () => {
  const home = await tempHome();
  await install(home, ['claude']);
  const [bot] = await findInstalled(home);
  // Before the delete starts, the bot's files are swapped for a different bot with the same name.
  const folder = join(home, '.claude', 'skills', 'study-buddy');
  const agent = join(home, '.claude', 'agents', 'study-buddy.md');
  await rm(folder, { recursive: true });
  await rm(agent);
  await install(home, ['claude'], anotherStudyBuddy());

  const results = await removeBot(bot);

  assert.deepEqual(
    results.map((result) => [result.item.kind, result.ok]),
    [
      ['bundle', false],
      ['file', false],
    ],
  );
  assert.ok((await readFile(join(folder, 'SKILL.md'), 'utf8')).includes(OTHER_URL));
  assert.ok(existsSync(join(folder, 'skills', 'weekly-plan.md')));
  assert.ok((await readFile(agent, 'utf8')).includes(OTHER_URL));
});

test("works when one agent's skills folder is a link to another's", async () => {
  const home = await tempHome();
  await install(home, ['claude']);
  const folder = join(home, '.claude', 'skills', 'study-buddy');
  await writeFile(join(folder, 'my-notes.md'), 'notes\n');
  await mkdir(join(home, '.cursor'));
  await symlink(join(home, '.claude', 'skills'), join(home, '.cursor', 'skills'), 'junction');
  const [bot] = await findInstalled(home);

  const results = await removeBot(bot);

  assert.deepEqual(
    results.map((result) => [result.item.kind, result.ok, result.kept]),
    [
      ['bundle', true, true],
      ['file', true, false],
    ],
  );
  assert.equal(await readFile(join(folder, 'my-notes.md'), 'utf8'), 'notes\n');
});

test('never follows a link from a skills folder to a copy saved somewhere else', async () => {
  const home = await tempHome();
  const projects = join(home, 'projects');
  await applyPlan(planInstall(studyBuddy(), ['folder'], { home, cwd: projects }));
  await mkdir(join(home, '.claude', 'skills'), { recursive: true });
  await symlink(join(projects, 'study-buddy'), join(home, '.claude', 'skills', 'study-buddy'), 'junction');

  assert.deepEqual(await findInstalled(home), []);
  assert.ok(existsSync(join(projects, 'study-buddy', 'SKILL.md')));
});
